### PR TITLE
ngTap directive

### PR DESCRIPTION
**Pull request by georgy7**
It works only if you don't move your finger.

### CODE REVIEW

**Comment by marktopper** [comment]
Can you please make a [test](https://github.com/nglar/ngTouch/blob/master/tests/spec.js) for this?

**Comment by georgy7** [comment]
Maybe later. I am mainly a backend developer. I don't clearly understand, how these tests work.

**Comment by georgy7** [comment]
Ok, I understood. 5 sec.

**Comment by marktopper** [comment]
I can look into it then.

**EDIT**: Seems like you we replied at the same time 😆

**Comment by georgy7** [comment]
Why Travis says, the tests passes? Look at the logs.

```
Error: [$injector:modulerr] Failed to instantiate module ng due to:
	TypeError: 'undefined' is not an object (evaluating 'Function.prototype.bind.apply')
```

https://github.com/wardbell/bardjs/issues/34

Locally, I use PhantomJS2.

**Comment by georgy7** [comment]
I didn't add `karma.conf.js` and `package.json`, because I thought, the problem is only on my machine.

**Comment by marktopper** [comment]
I will look into this.

**Comment by marktopper** [comment]
It seems like this problem is not because of your pull request.
It also happens on the [`master`](https://travis-ci.org/nglar/ngTouch/jobs/191746912).

I will merge this and look into the issue. Thanks! 👍

**Comment by marktopper** [comment]
To let you know I have just fixed the test, and have merged this into master at #22 and tagged the release of [`1.0.2`](https://github.com/nglar/ngTouch/releases/tag/v1.0.2).

**Pull request merged**
